language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - make build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $TRAVIS_BUILD_DIR/dist/teller
  skip_cleanup: true
  on:
    tags: false
