language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  # - make build
  - cl -l teller-executable -e '(asdf:make :teller-executable :build-pathname "foobar")'
  - pwd
  - echo $TRAVIS_BUILD_DIR
  - ls -alh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "teller"
  skip_cleanup: true
  draft: true
  on:
    tags: true
