language: common-lisp
sudo: required

# env:
  # matrix:
    # - LISP=sbcl

install:
  # Install cl-travis
  # - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  - sudo apt-get install buildapp

script:
  # - make build
  # - cl -l teller-executable -e '(asdf:make :teller-executable)'
  - buildapp --output teller --entry teller:tell --load-system teller-executable --asdf-path $TRAVIS_BUILD_DIR
  - pwd
  - ls -alh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "teller"
  skip_cleanup: true
  draft: true
  on:
    tags: true
